### ISSUE TITLE
How do you compile it?

### ISSUE THREAD

**Issue by energetictree** [duarteocarmo/coronabar#1]
I tried to compiled and it can compiled however when I tried to run it gives error with button Open Console and terminate.

**Comment by duarteocarmo** [comment]
You need to use py2app. [Here are the instructions in the rumps documentation](https://rumps.readthedocs.io/en/latest/creating.html). 

However, I have seen that error before in the computers of some users. Users with older macOS versions than mine are getting that error. 

Can you give me a bit more details?

**Comment by energetictree** [comment]
After followed the hint from https://stackoverflow.com/questions/59519402/py2app-modules-not-found-conditional-imports by running ./dist/XXX.app/Contents/MacOS/XXX from terminal
there is error:
ModuleNotFoundError: No module named 'pkg_resources.py2_warn'

Issue resolved after compiled with:
python3 setup.py py2app --packages=pkg_resources

thanks
