### ISSUE TITLE
coronabar doesn't keep state

### ISSUE THREAD

**Issue by lapisdecor** [duarteocarmo/coronabar#3]
When we select a country, if we close the app, it always return to USA. It should keep the previously selected country when we reopen.

**Comment by duarteocarmo** [comment]
Good point. Not sure how I would go about that. Probably would need to keep track of it somewhere in the filesystem or some sort of storage..

**Comment by duarteocarmo** [comment]
Closing this for now @lapisdecor, let me know if you have some ideas and want to reopen!

**Comment by TheTechRobo** [comment]
I feel like because macOS and Linux have a similar directory structure, the Linux version won't have to have a different path. Maybe `~/.coronabar/config.ini` or `~/.coronabar/config.xml` depending on whether you use INI or XML.

**Comment by TheTechRobo** [comment]
Just remembered I didn't leave a comment here.

I think it could be stored in a config file like #8.
