### ISSUE TITLE
Some strings must be split into separate words

### ISSUE THREAD

**Issue by StarkBjorn** [duarteocarmo/coronabar#5]
Some strings (screenshot below) contain several words but the words aren't separated with white spaces. This make them hardly readable.

If saving space is needed strings like "Testsperonemillion" could be turned into "Tests/million".

Installation: **snap**

Screenshot:
![Screenshot_2020-06-21](https://user-images.githubusercontent.com/31912752/85223039-7b331d80-b3c8-11ea-81f3-2868d445657e.png)

**Comment by duarteocarmo** [comment]
Hey @StarkBjorn, thanks for the input. @lapisdecor can you possibly update your [string mapper](https://github.com/duarteocarmo/coronabar/blob/335035f7e3ff4867976e69b3132a53b184b48bcf/Ubuntu/app.py#L113) to support this? 

@StarkBjorn, give it a try if you want as well. The code is pretty straightforward in that section!!
