### ISSUE TITLE
Unfriendly names

### ISSUE THREAD

**Issue by TheTechRobo** [duarteocarmo/coronabar#7]
Seems like some of the names are not friendly -- they're most likely variable names. Here is what it  currently shows:

```
Select Country >
About
Country: Canada
Cases: 113515
Cases Today: 309
Deaths: 8885
Deaths Today: 4
Recovered: 99111
Active: 5519
Critical: 2221
Per Million: 3006
deathsPerOneMillion: 235
totalTests: 3717483
testsPerOneMillion: 98442
Updated at 14:34
Quit
```
As you can see: `deathsPerOneMillion` instead of `Deaths Per Million` or something. Restarting the app does nothing. Switching back to the US does nothing. :thinking:

PS Great app!

**Comment by duarteocarmo** [comment]
Hey @TheTechRobo, I have created a [new release](https://github.com/duarteocarmo/coronabar/releases/tag/v2.5.0) of the mac app that includes changes to those names, and human readable numbers to make reading easier. 

@lapisdecor can you please update the linux version as well? (all new changes should be in `app.py`)

**Comment by lapisdecor** [comment]
I will do it asap.

A terça, 28/07/2020, 10:40, Duarte OC <notifications@github.com> escreveu:

**Comment by duarteocarmo** [comment]
@lapisdecor thanks a lot. Let me know if you have any issues.

**Comment by duarteocarmo** [comment]
In the meantime @lapisdecor  I will leave this issue open. If you don't mind closing it when you have patched things on the linux side I would greatly appreciate it!

Um abraço

**Comment by lapisdecor** [comment]
Ok. Abraço.

A terça, 28/07/2020, 10:46, Duarte OC <notifications@github.com> escreveu:

**Comment by TheTechRobo** [comment]
Hello!

>created a new release

I'll test it in a bit :)

**Comment by TheTechRobo** [comment]
Works fine for me! :D 

PS Awesome program!

**Comment by duarteocarmo** [comment]
Thanks for testing and for the feedback. I’ll leave this open for @lapisdecor to apply the same changes in the linux version!

**Comment by lapisdecor** [comment]
> Thanks for testing and for the feedback. I’ll leave this open for @lapisdecor to apply the same changes in the linux version!

I think I've done before on a previous PR. Please run the Linux version and tell me if everything is ok.

**Comment by duarteocarmo** [comment]
@lapisdecor hey, can you link me to that PR? I have updated some components I think you haven't updated on the linux side of things. 

- [Here for example - I implemented a human readable format of the numbers.](https://github.com/duarteocarmo/coronabar/blob/eb261a72f57f7af787e8493af85cf805184b3016/app.py#L92)
- [And here I added additional mappings for strings](https://github.com/duarteocarmo/coronabar/blob/eb261a72f57f7af787e8493af85cf805184b3016/app.py#L109)

Let me know if that makes sense!

**Comment by lapisdecor** [comment]
I think I have only the additional mappings for strings

[here](https://github.com/duarteocarmo/coronabar/blob/eb261a72f57f7af787e8493af85cf805184b3016/Ubuntu/app.py#L112)

**Comment by lapisdecor** [comment]
It's not exactly like yours, I think.
I can try to make it uniform on both versions but not right now.

**Comment by duarteocarmo** [comment]
Fair enough!
